spring:
  datasource:
    hikari:
      url: jdbc:h2:mem:test;
      driver-class-name: org.h2.Driver
      username: sa
      password:
      data: classpath:db/teardown.sql
      initialization-mode: always
      maximum-pool-size: 100
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000
  h2:
    console:
      enabled: true